// Mocks generated by Mockito 5.3.2 from annotations
// in clean_architecture_tdd_course/test/presentation/bloc/trivia_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture_tdd_course/core/error/failures.dart' as _i5;
import 'package:clean_architecture_tdd_course/core/util/input_converter.dart'
    as _i8;
import 'package:clean_architecture_tdd_course/domain/entities/trivia_entity.dart'
    as _i6;
import 'package:clean_architecture_tdd_course/domain/use_cases/get_random_trivia_use_case.dart'
    as _i7;
import 'package:clean_architecture_tdd_course/domain/use_cases/get_trivia_use_case.dart'
    as _i3;
import 'package:either_dart/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTriviaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTriviaUseCase extends _i1.Mock implements _i3.GetTriviaUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>> run(int? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #run,
          [input],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
            _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #run,
            [input],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
                _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #run,
            [input],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>);
}

/// A class which mocks [GetRandomTriviaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomTriviaUseCase extends _i1.Mock
    implements _i7.GetRandomTriviaUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>> run() => (super.noSuchMethod(
        Invocation.method(
          #run,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
            _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #run,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
                _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #run,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i8.InputConverter {
  @override
  _i2.Either<_i5.Failure, int> stringToUnsignedInteger(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToUnsignedInteger,
          [str],
        ),
        returnValue: _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
        returnValueForMissingStub: _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #stringToUnsignedInteger,
            [str],
          ),
        ),
      ) as _i2.Either<_i5.Failure, int>);
}
