// Mocks generated by Mockito 5.3.2 from annotations
// in clean_architecture_tdd_course/test/data/repositories/trivia_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture_tdd_course/core/network/network_info.dart'
    as _i6;
import 'package:clean_architecture_tdd_course/data/datasources/trivia_local_data_source.dart'
    as _i5;
import 'package:clean_architecture_tdd_course/data/datasources/trivia_remote_data_source.dart'
    as _i3;
import 'package:clean_architecture_tdd_course/data/models/trivia_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTriviaModel_0 extends _i1.SmartFake implements _i2.TriviaModel {
  _FakeTriviaModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TriviaRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTriviaRemoteDataSource extends _i1.Mock
    implements _i3.TriviaRemoteDataSource {
  @override
  _i4.Future<_i2.TriviaModel> getTrivia(int? number) => (super.noSuchMethod(
        Invocation.method(
          #getTrivia,
          [number],
        ),
        returnValue: _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getTrivia,
            [number],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getTrivia,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.TriviaModel>);
  @override
  _i4.Future<_i2.TriviaModel> getRandomTrivia() => (super.noSuchMethod(
        Invocation.method(
          #getRandomTrivia,
          [],
        ),
        returnValue: _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getRandomTrivia,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getRandomTrivia,
            [],
          ),
        )),
      ) as _i4.Future<_i2.TriviaModel>);
}

/// A class which mocks [TriviaLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTriviaLocalDataSource extends _i1.Mock
    implements _i5.TriviaLocalDataSource {
  @override
  _i4.Future<_i2.TriviaModel> getLastTrivia() => (super.noSuchMethod(
        Invocation.method(
          #getLastTrivia,
          [],
        ),
        returnValue: _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getLastTrivia,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TriviaModel>.value(_FakeTriviaModel_0(
          this,
          Invocation.method(
            #getLastTrivia,
            [],
          ),
        )),
      ) as _i4.Future<_i2.TriviaModel>);
  @override
  _i4.Future<void> cacheTrivia(_i2.TriviaModel? triviaToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTrivia,
          [triviaToCache],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
