// Mocks generated by Mockito 5.3.2 from annotations
// in clean_architecture_tdd_course/test/domain/usecases/get_trivia_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture_tdd_course/core/error/failures.dart' as _i5;
import 'package:clean_architecture_tdd_course/domain/entities/trivia_entity.dart'
    as _i6;
import 'package:clean_architecture_tdd_course/domain/repositories/trivia_repository_contract.dart'
    as _i3;
import 'package:either_dart/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TriviaRepositoryContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockTriviaRepositoryContract extends _i1.Mock
    implements _i3.TriviaRepositoryContract {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>> getTrivia(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrivia,
          [number],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
            _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #getTrivia,
            [number],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
                _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #getTrivia,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>> getRandomTrivia() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomTrivia,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
            _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #getRandomTrivia,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>.value(
                _FakeEither_0<_i5.Failure, _i6.Trivia>(
          this,
          Invocation.method(
            #getRandomTrivia,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Trivia>>);
}
